Repository ml4ai/automates, pull requests merged in 2020-03, with the labels that each got.

#108 Apis masha
  text_reading/sparql/sparqlWrapper.py
  text_reading/src/main/resources/application.conf
  text_reading/src/main/scala/org/clulab/aske/automates/OdinEngine.scala
  text_reading/src/main/scala/org/clulab/aske/automates/alignment/Aligner.scala
  text_reading/src/main/scala/org/clulab/aske/automates/apps/ExtractAndAlign.scala
  text_reading/src/main/scala/org/clulab/aske/automates/entities/StringMatchEntityFinder.scala
  text_reading/src/main/scala/org/clulab/aske/automates/grfn/GrFNParser.scala
  text_reading/src/main/scala/org/clulab/grounding/Grounder.scala
  text_reading/webapp/app/controllers/HomeController.scala
  text_reading/webapp/conf/routes
Labels: enhancement

#117 TR webapp hotfix
  .gitignore
  src/text_reading/webapp/public/brat/client/lib/head.load.min.js
  src/text_reading/webapp/public/brat/client/lib/jquery-ui-1.8.16.custom.min.js
  src/text_reading/webapp/public/brat/client/lib/jquery-ui.combobox.js
  src/text_reading/webapp/public/brat/client/lib/jquery-ui.min.js
  src/text_reading/webapp/public/brat/client/lib/jquery.ba-bbq.min.js
  src/text_reading/webapp/public/brat/client/lib/jquery.json.min.js
  src/text_reading/webapp/public/brat/client/lib/jquery.min.js
  src/text_reading/webapp/public/brat/client/lib/jquery.svg.min.js
  src/text_reading/webapp/public/brat/client/lib/jquery.svgdom.min.js
  src/text_reading/webapp/public/brat/client/lib/sprintf.js
  src/text_reading/webapp/public/brat/client/lib/webfont.js
Labels: bug

#119 Updating GrFN to new JSON I/O format
  requirements.txt
  scripts/model_analysis/pet_fib_comparison.py
  src/apps/CodeExplorer/cyjs.py
  src/model_analysis/networks.py
  src/program_analysis/for2py/genPGM.py
  tests/Dockerfile
  tests/data/GrFN/petpt_cag_edges.txt
  tests/data/GrFN/petpt_grfn_edges.txt
  tests/data/program_analysis/SIR-Gillespie-MS.f
  tests/model_analysis/test_GrFN.py
  tests/model_analysis/test_webapp.py
  tests/program_analysis/test_program_analysis.py
Labels: bug, enhancement
