Repository ml4ai/automates, pull requests merged in 2020-04, with the labels that each got.

#129 Adding TeX2Py script
  scripts/equation_reading/tex2py.py
Labels: ER Team

#132 svo query terms added to text_var link element
  src/text_reading/src/main/scala/org/clulab/aske/automates/apps/ExtractAndAlign.scala
  src/text_reading/src/main/scala/org/clulab/aske/automates/grfn/GrFNParser.scala
  src/text_reading/src/main/scala/org/clulab/grounding/Grounder.scala
Labels: Mid Priority, TR Team

#121 Endpoint modification
  requirements.txt
  scripts/model_analysis/pet_link_tables.py
  scripts/program_analysis/PETASCE_simple.py
  scripts/program_analysis/PETASCE_simple_preprocessed.f
  scripts/program_analysis/PETASCE_simple_preprocessed.xml
  scripts/program_analysis/PETASCE_simple_variable_map.pkl
  scripts/program_analysis/modFileLog.json
  scripts/program_analysis/rectified_PETASCE_simple.xml
  scripts/text_reading/extract_align_ground.py
  scripts/text_reading/svo_grounding_viewer.py
  src/text_reading/.sbtopts
  src/text_reading/build.sbt
  src/text_reading/sparql/sparql.py
  src/text_reading/sparql/sparqlQuery.sparql
  src/text_reading/sparql/sparqlWrapper.py
  src/text_reading/src/main/resources/application.conf
  src/text_reading/src/main/scala/org/clulab/aske/automates/OdinEngine.scala
  src/text_reading/src/main/scala/org/clulab/aske/automates/alignment/Aligner.scala
  src/text_reading/src/main/scala/org/clulab/aske/automates/apps/ExtractAndAlign.scala
  src/text_reading/src/main/scala/org/clulab/aske/automates/grfn/GrFNParser.scala
  src/text_reading/src/main/scala/org/clulab/grounding/Grounder.scala
  src/text_reading/webapp/app/controllers/HomeController.scala
  src/text_reading/webapp/project/build.properties
  tests/Dockerfile
Labels: High Priority, TR Team

#140 Updating link table viewer
  scripts/model_analysis/grfn_links_to_csv.py
  scripts/text_reading/alignment2link_graph.py
  scripts/text_reading/extract_align_ground.py
  src/model_analysis/linking.py
  tests/data/model_analysis/PEN-alignment.json
  tests/model_analysis/test_GrFN.py
  tests/model_analysis/test_linking.py
Labels: High Priority, MA Team, TR Team

#141 Visually meaningful data flow paths in GrFN
  scripts/model_analysis/grfn2pdf.py
  src/model_analysis/networks.py
Labels: Low Priority, MA Team, enhancement

#139 Issue130
  scripts/equation_reading/PETASCE_py_eqns.txt
  scripts/equation_reading/tex2py.py
  src/equation_reading/decoding.py
  src/equation_reading/latex_tokenizer.py
  tests/data/equation_reading/sample_equations.txt
  tests/data/equation_reading/sample_output.txt
  tests/equation_reading/test_tex2py.py
Labels: ER Team, Mid Priority
